let commentValidation = {
  id: "/Comment",
  type: "object",
  properties: {
    profile_id: { type: "string" },
    commentator_id: { type: "string" },
    mbti: {
      type: "string",
      enum: [
        "INFP",
        "INFJ",
        "ENFP",
        "INTJ",
        "INTP",
        "ENTP",
        "ENTJ",
        "ISFP",
        "ESFP",
        "ESFJ",
        "ISTP",
        "ISTJ",
        "ESTP",
        "ESTJ",
      ],
    },
    enneagram: {
      type: "string",
      enum: [
        "1w2",
        "2w3",
        "3w2",
        "3w4",
        "4w3",
        "4w5",
        "5w4",
        "5w6",
        "6w5",
        "6w7",
        "7w6",
        "7w8",
        "8w7",
        "8w9",
        "9w8",
        "9w1",
      ],
    },
    zodiac: {
      type: "string",
      enum: [
        "Aries",
        "Taurus",
        "Gemini",
        "Cancer",
        "Leo",
        "Virgo",
        "Libra",
        "Scorpio",
        "Sagittarius",
        "Capricorn",
        "Aquarius",
        "Pisces",
      ],
    },
    likes: { type: "integer" },
  },
  required: ["profile_id", "commentator_id", "title"],
};

module.exports = commentValidation;
